"""initial

Revision ID: 8597d83fe709
Revises: 
Create Date: 2026-05-24 19:29:52.169760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8597d83fe709'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('doador', 'ong', 'admin', name='tipo_usuario_enum'), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('doacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doador_id', sa.Integer(), nullable=False),
    sa.Column('tipo_alimento', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('cadastrado', 'analisado', 'matched', 'notificado', 'coletado', 'confirmado', 'cancelado', name='status_doacao_enum'), nullable=False),
    sa.Column('urgencia', sa.Enum('baixa', 'media', 'alta', 'critica', name='urgencia_enum'), nullable=False),
    sa.Column('score_matching', sa.Float(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doador_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doacoes_doador_id'), 'doacoes', ['doador_id'], unique=False)
    op.create_index(op.f('ix_doacoes_status'), 'doacoes', ['status'], unique=False)
    op.create_table('ongs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('capacidade_atendimento', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('historico_atendimento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ong_id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Date(), nullable=False),
    sa.Column('quantidade_atendida', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ong_id'], ['ongs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_atendimento_ong_id'), 'historico_atendimento', ['ong_id'], unique=False)
    op.create_table('logs_afd',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doacao_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=50), nullable=False),
    sa.Column('estado_novo', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['doacao_id'], ['doacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_afd_doacao_id'), 'logs_afd', ['doacao_id'], unique=False)
    op.create_table('scores_matching',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doacao_id', sa.Integer(), nullable=False),
    sa.Column('ong_id', sa.Integer(), nullable=False),
    sa.Column('urgencia_peso', sa.Float(), nullable=False),
    sa.Column('demanda_peso', sa.Float(), nullable=False),
    sa.Column('distancia_peso', sa.Float(), nullable=False),
    sa.Column('score_final', sa.Float(), nullable=False),
    sa.Column('calculado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doacao_id'], ['doacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ong_id'], ['ongs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores_matching')
    op.drop_index(op.f('ix_logs_afd_doacao_id'), table_name='logs_afd')
    op.drop_table('logs_afd')
    op.drop_index(op.f('ix_historico_atendimento_ong_id'), table_name='historico_atendimento')
    op.drop_table('historico_atendimento')
    op.drop_table('ongs')
    op.drop_index(op.f('ix_doacoes_status'), table_name='doacoes')
    op.drop_index(op.f('ix_doacoes_doador_id'), table_name='doacoes')
    op.drop_table('doacoes')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
