"""add_performance_indexes

Revision ID: f6db5939b74b
Revises: bdbbd4a97c03
Create Date: 2026-05-25 21:28:57.833148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6db5939b74b'
down_revision: Union[str, None] = 'bdbbd4a97c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_historico_atendimento_semana'), 'historico_atendimento', ['semana'], unique=False)
    op.create_index('ix_logs_afd_doacao_timestamp', 'logs_afd', ['doacao_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_scores_matching_doacao_id'), 'scores_matching', ['doacao_id'], unique=False)
    op.create_index(op.f('ix_scores_matching_ong_id'), 'scores_matching', ['ong_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_matching_ong_id'), table_name='scores_matching')
    op.drop_index(op.f('ix_scores_matching_doacao_id'), table_name='scores_matching')
    op.drop_index('ix_logs_afd_doacao_timestamp', table_name='logs_afd')
    op.drop_index(op.f('ix_historico_atendimento_semana'), table_name='historico_atendimento')
    # ### end Alembic commands ###
